baseURL = 'https://rudolfj.github.io'
languageCode = 'en-us'
title = 'Rudolf J Schnetler'
theme = 'typo'

[params]
theme = 'auto'
colorPalette = 'eink'
#showFooter = true
#footerContent = "Your **custom** md `footer`"

homeIntroTitle = "Contact Me"
homeIntroContent = """

"""

[[params.social]]
name = "linkedin"
url = "https://www.linkedin.com/in/rudolfj/"

[[params.social]]
name = "orcid"
url = "https://orcid.org/0000-0001-5129-5601"

[[params.social]]
name = "github"
url = "https://github.com/rudolfjs/"

[[params.social]]
name = "kaggle"
url = "https://www.kaggle.com/samplevariance"
