title = "Social Media Links"

[owner]
name = "Rudolf J"

[social]
[social.github]
url = "https://github.com/rudolfjs/"
[social.linkedin]
url = "https://www.linkedin.com/in/rudolfj/"
[social.kaggle]
url = "https://www.kaggle.com/samplevariance"
[social.orcid]
url = "https://orcid.org/0000-0001-5129-5601"
